---
- set_fact:
    arch: linux_amd64
  when: ansible_system == "Linux"

- set_fact:
    arch: darwin_amd64
  when: ansible_system == "Darwin"

- name: Downloads Package
  get_url: >
    url="{{ nomad_install.download_location}}/{{ nomad_app.version }}/{{ nomad_app.name }}_{{ nomad_app.version }}_{{ arch }}.zip"
    dest="/tmp/{{ nomad_app.name }}_{{ nomad_app.version }}_{{ arch }}.zip"
    mode=0755
    force={{ nomad_install.force_download | default(false)}}
    validate_certs=no
  sudo: no
  tags:
    - hashicorp
    - nomad
    - install
    - download

- name: Unpacks to location
  unarchive: >
    src=/tmp/{{ nomad_app.name }}_{{ nomad_app.version }}_{{ arch }}.zip
    dest={{ nomad_install.dir }}
    copy=no
    mode=755
  sudo: yes
  tags:
    - hashicorp
    - nomad
    - install
    - unarchive

- name: Fix permissions on files (Workaround while waiting for 2.0)
  file: path={{ nomad_install.dir }}/{{ item }}
    owner={{ file_owner | default('root') }}
    group={{ file_group | default('staff') }}
    mode=755
  sudo: yes
  with_items:
    - "{{ nomad_install.file_list }}"
  tags:
    - hashicorp
    - nomad
    - install
    - workaround
