---
- name: Downloads Package
  get_url: >
    url="{{ install.download_location}}/{{ app.name }}_{{ app.version }}_{{ app.arch }}.zip"
    dest="/tmp/{{ app.name }}_{{ app.version }}_{{ app.arch }}.zip"
    mode=0755
  sudo: no
  tags:
    - hashicorp
    - nomad
    - install
    - download

- name: Unpacks to location
  unarchive: >
    src=/tmp/{{ app.name }}_{{ app.version }}_{{ app.arch }}.zip
    dest={{ install.dir }}
    copy=no
    mode=750
  sudo: yes
  tags:
    - hashicorp
    - nomad
    - install
    - unarchive

- name: Fix permissions on files (Workaround while waiting for 2.0)
  file: path={{ install.dir }}/{{ item }}
    owner={{ app.file_owner | default('root') }}
    group={{ app.file_group | default('root') }}
    mode=750
  sudo: yes
  with_items:
    - "{{ install.file_list }}"
  tags:
    - hashicorp
    - nomad
    - install
    - workaround
